name: Java with Maven >> print on Master repo

on:
  push:
    branches:  ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Run at DEV print
        run: echo "Hello my new world"
