name: Java with Maven >> Master

on:
  push:
    branches:  ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Run print
        run: echo "Hello my new world"