name: Java with Maven - print world

on:
  push:
    branches:  ["ci-demo_noTest_yml"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Run print
        run: echo "Hello my new world"